### PR TITLE
fix: Modify the way of parse and validate mongo url

### PR DESCRIPTION
**Pull request by SoaringTiger**
Fix: #39 
There is an mongodb official package "go.mongodb.org/mongo-driver/x/mongo/driver/connstring" will solve it.
And databaseName just use connString.Database value.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@closetool plz review.

**Review by closetool — APPROVED** [review]

**Comment by hsluoyz** [comment]
@closetool plz make a new release.

**Comment by closetool** [comment]
@hsluoyz sorry, but I have no permission

**Comment by hsluoyz** [comment]
@closetool try again.

**Comment by hsluoyz** [comment]
@SoaringTiger released: https://github.com/casbin/mongodb-adapter/releases/tag/v3.1.1

**Pull request merged**
