### PR TITLE
use unique index

### PR DESCRIPTION
**Pull request by lxzan**
Fix: https://github.com/casbin/mongodb-adapter/issues/27

### CODE REVIEW

**Comment by lxzan** [comment]
use unique index

**Comment by hsluoyz** [comment]
@lxzan fix DCO.

**Comment by hsluoyz** [comment]
@nodece @dovics @00LT00 please review.

**Comment by nodece** [comment]
@hsluoyz I not sure there are has breaking change.

**Comment by hsluoyz** [comment]
@nodece we can make a major release.

**Comment by geekgonecrazy** [comment]
When upgrading to v3 I assume we need to drop the index?

> panic: (IndexKeySpecsConflict) An existing index has the same name as the requested index. When index names are not specified, they are auto generated and can cause conflicts. Please refer to our documentation. Requested index: { v: 2, unique: true, key: { ptype: 1, v0: 1, v1: 1, v2: 1, v3: 1, v4: 1, v5: 1 }, name: "ptype_1_v0_1_v1_1_v2_1_v3_1_v4_1_v5_1" }, existing index: { v: 2, key: { ptype: 1, v0: 1, v1: 1, v2: 1, v3: 1, v4: 1, v5: 1 }, name: "ptype_1_v0_1_v1_1_v2_1_v3_1_v4_1_v5_1" }

**Comment by geekgonecrazy** [comment]
Understood it being a major issue what lead me to searching the repo.  But the release notes don't mention anything.  Might be useful to add a note about upgrading requiring recreating the index

**Pull request merged**
