### PR TITLE
increment major version to v3 and update dependencies

### PR DESCRIPTION
**Pull request by alexferl**
@hsluoyz as requested, I incremented the version so we can use #27.

Fix: https://github.com/casbin/mongodb-adapter/issues/27#issuecomment-696454609

### CODE REVIEW

**Comment by alexferl** [comment]
@hsluoyz thank you, but I am getting the following error:
```
go get -u github.com/casbin/mongodb-adapter/v3
go get github.com/casbin/mongodb-adapter/v3: module github.com/casbin/mongodb-adapter@upgrade found (v1.0.0), but does not contain package github.com/casbin/mongodb-adapter/v3
```

You need to update the v3.0.0 tag I think?

**Comment by hsluoyz** [comment]
@alexferl we already have v3.0.0 tag: https://github.com/casbin/mongodb-adapter/releases/tag/v3.0.0

**Comment by arshadrk** [comment]
@hsluoyz In Existing tag v3.0.0, the module is mentioned as "github.com/casbin/mongodb-adapter/v2" in mod.go which is fixed by this PR. 

So "go get -u github.com/casbin/mongodb-adapter/v3" will be failing as the version mentioned in released v3.0.0 is v2 in go.mod file. This makes it impossible to update to latest version(v3.0.0).

Please update the release v3.0.0 to include this PR or please delete the existing release V3.0.0 and create a new release named the same v3.0.0 with the current head of master(which includes this PR).

**Comment by hsluoyz** [comment]
@arshadrk done: https://github.com/casbin/mongodb-adapter/releases/tag/v3.0.0

**Pull request merged**
